export { default as brain } from './brain'
export { default as modal } from './modal'
export { default as ears } from './ears'
export { default as mouth } from './mouth'
export { default as system } from './system'